<?php

namespace ContainerAo3qKCB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NDTE3hgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NDTE3hg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NDTE3hg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'carRepository' => ['privates', 'App\\Repository\\CarRepository', 'getCarRepositoryService', true],
            'schedulesRepository' => ['privates', 'App\\Repository\\SchedulesRepository', 'getSchedulesRepositoryService', true],
        ], [
            'carRepository' => 'App\\Repository\\CarRepository',
            'schedulesRepository' => 'App\\Repository\\SchedulesRepository',
        ]);
    }
}
