<?php

namespace Container6jSNAW8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YNvC0OiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YNvC0Oi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YNvC0Oi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reviewRepository' => ['privates', 'App\\Repository\\ReviewRepository', 'getReviewRepositoryService', true],
            'schedulesRepository' => ['privates', 'App\\Repository\\SchedulesRepository', 'getSchedulesRepositoryService', true],
            'serviceRepository' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
        ], [
            'reviewRepository' => 'App\\Repository\\ReviewRepository',
            'schedulesRepository' => 'App\\Repository\\SchedulesRepository',
            'serviceRepository' => 'App\\Repository\\ServiceRepository',
        ]);
    }
}
