<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAo3qKCB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAo3qKCB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAo3qKCB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAo3qKCB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAo3qKCB\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ao3qKCB',
    'container.build_id' => '544201ba',
    'container.build_time' => 1708701763,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAo3qKCB');
